---
version: "3.8"

services:
  api:
    platform: linux/arm64
    container_name: dock_api
    build: ./.docker/golang
    environment:
      ENV: test
      DB_TYPE: postgres
      DSN=dbname: 'dock sslmode=disable user=admin password=admin host=localhost'
      DB_TYPE_TEST: sqlite3
      DSN_TEST: ':memory:'
      DEBUG: true
      AUTO_MIGRATE_DB: true
      PORT: 8080
    volumes:
      - .:/go/src/
    ports:
      - 8080:8080
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  postgres:
    container_name: dock_postgres
    build: ./.docker/postgress
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dock
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin

volumes:
  pgdata:


