---
version: "3.8"

services:
  api:
    platform: linux/arm64
    container_name: dock_api
    build: ./.docker/golang
    volumes:
      - .:/go/src/
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  postgres:
    container_name: dock_postgres
    build: ./.docker/postgress
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=dock
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin

volumes:
  pgdata:


