FROM golang:1.19

WORKDIR /go/src
COPY . .

ENV CGO_CFLAGS="-g -O2 -Wno-return-local-addr"

RUN apt-get update && apt-get install build-essential -y
RUN go build -o /go/bin/dock main.go 

CMD ["/go/bin/dock"]